#!/bin/sh
arch=$(uname -m)
emsdk_version=3.1.73

if [[ "$arch" == "arm64" || "$arch" == "aarch64" ]]; then
  docker build -t lok-wasm:$emsdk_version --build-arg ARCH=-arm64 --build-arg VER=$emsdk_version .
else
  docker build -t lok-wasm:$emsdk_version --build-arg VER=$emsdk_version .
fi
mkdir -p .cache .npm

exec docker run \
  --rm \
  -it \
  -v $(pwd)/libreoffice-core:/libreoffice-core \
  -v $(pwd)/scripts:/scripts \
  -v $(pwd)/VERSION:/VERSION \
  -v $(pwd)/soffice_fccache.data:/soffice_fccache.data \
  -v $(pwd)/soffice_fccache.data.js.metadata:/soffice_fccache.data.js.metadata \
  -v $(pwd)/.cache:/.cache:rw \
  -v $(pwd)/.npm:/.npm:rw \
  -u $(id -u):$(id -g) \
  -w / \
  lok-wasm:$emsdk_version \
  bash
