#!/bin/bash

set -e

BASE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE:-$0}")"/.. &>/dev/null && pwd)
FILE_PACKAGER="$BASE_DIR/emsdk/upstream/emscripten/tools/file_packager"
FCCACHE_FILE="soffice_fccache.data"
METADATA_SUFFIX=".js.metadata"
FCCAHCE_OUT="$BASE_DIR/libreoffice-core/instdir/program/$FCCACHE_FILE"
QA_ENV_DIR="$BASE_DIR/qa-env"

# Add emscripten toolchain
cd "$BASE_DIR/libreoffice-core"
  echo "Generating FcCache"
  cp "$BASE_DIR/$FCCACHE_FILE" "$FCCAHCE_OUT"
  cp "$BASE_DIR/$FCCACHE_FILE$METADATA_SUFFIX" "$FCCAHCE_OUT$METADATA_SUFFIX"
