#!/bin/bash

set -e
BASE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE:-$0}")"/.. &>/dev/null && pwd)
BUILD_DIR="$BASE_DIR/build"

mkdir "$BUILD_DIR" &>/dev/null || true;

cd "$BASE_DIR/libreoffice-core/instdir/program";

echo 'Copying files...'
cp ./*.wasm ./*.data ./*.mjs ./*.js ./*.d.ts ./*.metadata "$BUILD_DIR"

cd "$BUILD_DIR"
rm fccache.* fccache_worker.* bindings_uno.* webgl2_draw_image.* || true;

if [ "$1" != "no-wasm" ]; then
echo 'Compressing files...'
brotli ./*.wasm ./*.data

for file in *.br; do
  mv -- "$file" "${file%.br}"
done
fi
