#!/bin/bash
COMMIT_DATE="2024-01-10"

if [ ! -e "$1" ]; then
  echo "Usage: $0 LIBREOFFICE_CORE_LOCAL_REPO"
  exit 1
fi
LO_CORE=$1
HERE="$(pwd)"

cd "$LO_CORE" || exit 1
# find all the commits after the initial commit date that update embind
git fetch origin master &&
  COMMITS=$(git rev-list --after=$COMMIT_DATE --reverse FETCH_HEAD -- \
    "static/source/embindmaker" \
    "static/source/unoembindhelpers" \
    "unotest/source/embindtest" \
    "static/Executable_embindmaker.mk" \
    "static/CustomTarget_unoembind.mk")

if [ -z "$COMMITS" ]; then
  echo 'No commits found'
  exit 1
fi

for i in $COMMITS; do
  echo 'Preparing patch for:'
  git log -1 --pretty="%ai %s" "$i"
done

TMP_DIR=$(mktemp -d)
PATCHES=()
for commit in $COMMITS; do
  PATCH="$TMP_DIR/${commit}.patch"
  echo "Preparing $PATCH"
  git format-patch -1 "$commit" --stdout >"$PATCH"
  PATCHES+=("$PATCH")
done

cd "$HERE" || exit 1

echo "Temp dir: $TMP_DIR"

OLD_HEAD=$(git log --format='%H' HEAD -1)
git am --3way --empty=drop --directory=libreoffice-core "${PATCHES[@]}"
git reset --soft HEAD~"$OLD_HEAD"
git commit -m "Squashed embind changes:"
git log --format="%h %s" "HEAD@{1}..HEAD@{0}" >> .git/COMMIT_EDITMSG
