#!/bin/bash
git fetch --no-tags --shallow-since=2024-02-20 https://github.com/LibreOffice/core distro/collabora/co-24.04
git subtree merge --prefix libreoffice-core FETCH_HEAD https://github.com/LibreOffice/core --squash
